### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by LionelColaso** [Epicguru/Melee-Animation#42]
Hugslib LOG

[MELEE_ANIMATION.txt](https://github.com/Epicguru/Melee-Animation/files/14622804/MELEE_ANIMATION.txt)

![image](https://github.com/Epicguru/Melee-Animation/assets/2488703/bab361e9-6a27-49cc-83dc-57f26f971e30)

![image](https://github.com/Epicguru/Melee-Animation/assets/2488703/a70d8b92-d9f6-42a5-8da5-efe22f91ee54)

**Comment by Epicguru** [comment]
These are warnings, not errors, and they are fine. Unless you are having issues in-game, this is not a problem.
